### ISSUE TITLE
likes and replies from other people displaying on the timeline

### ISSUE THREAD

**Issue by diegontijo** [ZusorCode/GoodTwitter#45]
is there a way to avoid replies and likes from other people to appear on the TL? this is the worst thing on twitter and I started using this addon exactly in order to avoid this problem

**Comment by mj-rich** [comment]
i'm also having this problem, started yesterday. i have an extensive set of mutes that worked really well before then (i've been using this plugin since the week it was made available).

**Comment by FeebsATE** [comment]
Having the same issue.

**Comment by goto-bus-stop** [comment]
Same, I'm now using a simple userstyle to hide replies and likes:
```css
.tweet[data-component-context="suggest_activity_tweet"],
.tweet[data-component-context="suggest_sc_tweet"] {
  display: none
}
```
